apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: krl-gw
  namespace: krl
  annotations:
    alb.networking.k8s.io/scheme: internal
    alb.networking.k8s.io/target-type: ip
spec:
  gatewayClassName: alb
  listeners:
    - name: http
      protocol: HTTP
      port: 80
